language: lua
install:
  - sudo apt-get update
  - sudo apt-get install openssl
  - sudo apt-get install libssl-dev
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luasec OPENSSL_DIR=/usr/lib
  - sudo luarocks install busted
  - sudo luarocks install lua-cjson
  - sudo luarocks install httpclient
script: "busted spec"
