language: lua
sudo: false
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - luajit
    - luarocks
    - lua-resty-http
    - openresty
    - cpanminus
env:
  - PERL5LIB=$HOME/perl5

install:  
  - luarocks build api_gateway-0.1-0.rockspec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu --local
  - cpanm --local-lib=$HOME/perl5 install Test::Nginx::Socket
script: ./scripts/run-tests.sh
