language: lua
install:
  - sudo apt-get update
  - sudo apt-get install openssl
  - sudo apt-get install libssl-dev
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install lua-resty-http 0.1-0
  - sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu/
  - sudo luarocks install busted 2.0.rc10-0
  - sudo luarocks install lua-cjson 2.1.0-1
  - sudo luarocks install httpclient 0.1.0-7
script: "busted spec"
