language: lua
sudo: false
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - luajit
    - luarocks
    - lua-resty-http

install:  
  - luarocks build api_gateway-0.1-0.rockspec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu --local
script: "~/.luarocks/bin/busted spec"
